name: mega-workflow

on:
  workflow_dispatch:

jobs:
  step1:
    uses: ./.github/workflows/flow1.yaml
    with:
      environment: dev
    secrets: inherit
  step2:
    uses: ./.github/workflows/flow1.yaml
    with:
      environment: test
    secrets: inherit
  step3:
    uses: ./.github/workflows/flow1.yaml
    with:
      environment: test
    secrets: inherit
