name: sub-workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: test
        shell: bash
        run: |
          echo "build ${{ inputs.environment }}"
  apply:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: test
        shell: bash
        run: |
          echo "deploy ${{ inputs.environment }}"
